#!/bin/sh
cd ${0%/*} || exit 1   

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication cartesianMesh
runApplication transformPoints -scale 1e-3


#------------------------------------------------------------------------------
